# Change these first
owner: learnasteve # Your GitHub organization or username, where this repository lives
repo: korero-upptime # The name of this repository

status-website:
  theme: dark

sites:
  - name: Huanui (login)
    url: https://lab.let.media.kyoto-u.ac.jp/korero/alive
  - name: Uranga (dashboard)
    url: https://lab.let.media.kyoto-u.ac.jp/korero/uranga/health
  - name: Uranga (db)
    url: https://lab.let.media.kyoto-u.ac.jp/korero/uranga/health/db
  - name: Tammy (app)
    url: https://lab.let.media.kyoto-u.ac.jp/korero/tammy/health
    icon: https://lab.let.media.kyoto-u.ac.jp/korero/static/tammy.jpg
  - name: Tammy (llm)
    url: https://lab.let.media.kyoto-u.ac.jp/korero/tammy/health/llm
  - name: Tammy (db)
    url: https://lab.let.media.kyoto-u.ac.jp/korero/tammy/health/db
  - name: Penny (app)
    url: https://lab.let.media.kyoto-u.ac.jp/korero/penny/health
  - name: Penny (llm)
    url: https://lab.let.media.kyoto-u.ac.jp/korero/penny/health/llm
  - name: Penny (db)
    url: https://lab.let.media.kyoto-u.ac.jp/korero/penny/health/db

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /korero-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Korero Upptime
  introTitle: "**Korero Whanau**"
  #introMessage: 
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
